version: "3.7"

services:
  forticlient:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CERTIFICATE_FILE=file.pfx
    image: hybirdcorp/docker-forticlient    
    environment:
      - VPNADDR=host:port
      - VPNUSER=me@domain
      - VPNPASS=secret
      - VPNTIMEOUT=${VPNTIMEOUT:-10}
      - CERTIFICATE=name.pfx
      - CERTFICATEPASS=secret
    network_mode: "host"
    privileged: true